apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-webservice1
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/SHUNSUKE-OHTSUKA/k8s-apps.git
      revision: HEAD
      directories:
      - path: webservice1/nginx/overlays/*
  template:
    metadata:
      name: '{{path.basename}}'
      labels:
        source-org: SHUNSUKE-OHTSUKA
        source-repo: k8s-apps
        source-branch: HEAD
    spec:
      project: appproject-webservice1
      source:
        repoURL: https://github.com/SHUNSUKE-OHTSUKA/k8s-apps.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: webservice1
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - PrunePropagationPolicy=background
        - ApplyOutOfSyncOnly=true
