apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server
  namespace: elastic-monitoring
spec:
  version: 8.9.2
  count: 1
  elasticsearchRef:
    name: monitoring-elasticsearch
  kibanaRef:
    name: monitoring-kibana
