apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" # https://github.com/argoproj/argo-cd/issues/2953#issuecomment-932190859
spec:
  ingressClassName: nginx
  rules:
  - host: argocd.minikube.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              name: http
  tls:
  - hosts:
    - argocd.minikube.local
    secretName: argocd-cert-secret

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
  namespace: elastic-monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
  - host: kibana.minikube.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: monitoring-kibana-kb-http
            port:
              number: 5601
  tls:
  - hosts:
    - kibana.minikube.local
    secretName: kibana-cert-secret

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elastic-apm-ingress
  namespace: elastic-monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
  - host: elastic-apm.minikube.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apm-server-apm-http
            port:
              number: 8200
  tls:
  - hosts:
    - elastic-apm.minikube.local
    secretName: elastic-apm-cert-secret

---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: kiali-ingress
#   namespace: istio-system
#   annotations:
#     nginx.ingress.kubernetes.io/secure-backends: "true"
#     nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: kiali.minikube.local
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: kiali
#             port:
#               number: 20001

#   tls:
#   - hosts:
#     - kiali.minikube.local
#     secretName: kiali-cert-secret
