apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: elastic-kube-state-metrics
    app.kubernetes.io/version: 2.10.0
  name: elastic-kube-state-metrics
  namespace: elastic-monitoring
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 8080
    targetPort: http-metrics
  - name: telemetry
    port: 8081
    targetPort: telemetry
  selector:
    app.kubernetes.io/name: elastic-kube-state-metrics
