apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sample-application
  namespace: argocd
spec:
  description: sample-application project
  sourceRepos:
    - "*"
  destinations:
    - namespace: app
      server: https://kubernetes.default.svc
    - namespace: database
      server: https://kubernetes.default.svc
    - namespace: default
      server: https://kubernetes.default.svc
