apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd
spec:
  sourceRepos:
    - "*"
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  roles:
    - name: power
      description: Power privileges to my-project.
      policies:
      - p, proj:my-project:power, applications, create, my-project/*, allow
      - p, proj:my-project:power, applications, get, my-project/*, allow
      - p, proj:my-project:power, applications, update, my-project/*, allow
      - p, proj:my-project:power, applications, delete, my-project/*, allow
      - p, proj:my-project:power, applications, sync, my-project/*, allow
    - name: edit
      description: edit privileges to my-project.
      policies:
      - p, proj:my-project:power, applications, create, my-project/*, allow
      - p, proj:my-project:power, applications, get, my-project/*, allow
      - p, proj:my-project:power, applications, update, my-project/*, allow
    - name: sync
      description: Sync privileges to my-project.
      policies:
        - p, proj:my-project:sync, applications, get, my-project/*, allow
        - p, proj:my-project:sync, applications, sync, my-project/*, allow
        - p, proj:my-project:sync, applications, action, my-project/*, allow
