apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  # policy.default: role:readonly
  policy.csv: |
    g, admin, role:admin
    g, dev, proj:my-project:power
    g, ope, proj:my-project:edit
    g, sync, proj:my-project:sync
